:noaudio:
:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= Dynamic Routing with Istio

== What is a Service Mesh?

As microservices-based applications become more prevalent, both the number of
and complexity of their interactions increases. Up until now much of the burden
of managing these complex microservices interactions has been placed on the
application developer, with different or non-existent support for microservice
concepts depending on language and framework.

The service mesh concept pushes this responsibility to the infrastructure, with
features for traffic management, distributed tracing and observability, policy
enforcement, and service/identity security, freeing the developer to focus on
business value. In this hands-on session you will learn how to apply some of
these features to a simple polyglot microservices application running on top of
OpenShift using Istio, an open platform to connect, manage, and secure
microservices.

== What is Istio?

Istio is an open platform to connect, manage, and secure microservices. Istio
provides an easy way to create a network of deployed services with load
balancing, service-to-service authentication, monitoring, and more, without
requiring any changes in application code. OpenShift can automatically inject a
special sidecar proxy throughout your environment to enable Istio management for
your application. This proxy intercepts all network communication between your
microservices microservices, and is configured and managed using Istio’s control
plane functionality -- not your application code!

== Lab Overview

There are three microservices in this lab and they are chained together in the following sequence:

`gateway -> partner -> catalog`

== Goals

In this lab, you will:

* Access the OpenShift environment
* Deploy microservice applications to OpenShift

== Environment Variables

Before getting started, you'll want to open a terminal window and set the following environment variables that will be used throughout the duration of this lab.

-----
######  Instructor will provide the values to these environment variables #######

$ export REGION=<provided by your instructor>
$ export OCP_USERNAME=<provided by your instructor>
$ export OCP_PASSWD=<provided by your instructor>

#  Using above variables, copy & paste the following in same terminal #

$ export OCP_TUTORIAL_PROJECT=$OCP_USERNAME-istio-tutorial
-----

=== OpenShift access

Your lab environment is built on Red Hat's OpenShift Container Platform.

Access to your OCP resources can be gained via both the `oc` utility as well as the OCP web console.

. Log into OpenShift
+
-----
$ oc login https://master.$REGION.openshift.opentlc.com -u $OCP_USERNAME -p $OCP_PASSWD
-----

. View existing projects:
+
-----
$ oc get projects

NAME                      DISPLAY NAME              STATUS
istio-system                                        Active
-----

.. Your OCP user has been provided with _view_ and _edit_ access to the central _istio-system_ namespace with all _control plane_ Istio functionality.
+
Later in this lab, you'll use a utility called _istioctl_ .
This utility will need both view and edit privileges to the _istio-system_ namespace.

.. Your OCP use has also been provided with _view_ access to a multi-tenant 

. Create a new tutorial project
+
----
$ oc new-project $OCP_TUTORIAL_PROJECT
----

. Set up permissions for the project
+
----
oc adm policy add-scc-to-user privileged -z default -n $OCP_TUTORIAL_PROJECT
----

. Switch to the tutorial project
+
----
$ oc project $OCP_TUTORIAL_PROJECT
----

== Clone Source Code

Start by cloning the tutorial source files to your computer.

. Open a terminal window and enter the following commands:
+
----
cd ~/

git clone https://github.com/gpe-mw-training/rhte-msa-and-service-mesh.git

cd rhte-msa-and-service-mesh
----

== Deploy Catalog service version 1 (`v1`)

Now let's start by deploying the catalog service to OpenShift. The sidecar proxy will automatically be injected.

. In your terminal window, enter the following commands:
+
----
cd catalog/java/vertx
mvn clean package
docker build -t example/catalog:v1 .
docker images | grep catalog

oc apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n $OCP_TUTORIAL_PROJECT
oc create -f ../../kubernetes/Service.yml
----

. Monitor the deployment of the pods. Enter the following command:
+
----
oc get pods -w
----

* Wait until the status for the catalog service is Running and there are 2/2 pods in the Ready column. To exit, press Ctrl+C

== Deploy Partner service 

Next, we will deploy the partner service to OpenShift. 

. In your terminal window, enter the following commands:
+
----
cd ~/rhte-msa-and-service-mesh

cd partner/java/springboot
mvn clean package
docker build -t example/partner:v1 .
docker images | grep partner

oc apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n $OCP_TUTORIAL_PROJECT
oc create -f ../../kubernetes/Service.yml
----

. Monitor the deployment of the pods. Enter the following command:
+
----
oc get pods -w
----

* Wait until the status for the partner service is Running and there are 2/2 pods in the Ready column. To exit, press Ctrl+C

== Deploy Gateway service

Finally, we will deploy the gateway service to OpenShift. This will complete our list of services: `gateway -> partner -> catalog`

. In your terminal window, enter the following commands:
+
----
cd ~/rhte-msa-and-service-mesh

cd customer/java/springboot
mvn clean package
docker build -t example/customer .
docker images | grep customer

oc apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n $OCP_TUTORIAL_PROJECT
oc create -f ../../kubernetes/Service.yml -n $OCP_TUTORIAL_PROJECT
----

. Monitor the deployment of the pods. Enter the following command:
+
----
oc get pods -w
----

* Wait until the status for the gateway service is Running and there are 2/2 pods in the Ready column. To exit, press Ctrl+C

=== Expose Gateway Service

. Since the `gateway` service is the one our users will interact with, let’s add an OpenShift Route that exposes that endpoint.
+
----
oc expose service gateway
----

. Retrieve the URL for the gateway service
+
----
$ export GATEWAY_URL=http://$(oc get route gateway-service -n $OCP_TUTORIAL_PROJECT -o template --template='{{.spec.host}}')

$ echo $GATEWAY_URL
----

. Test the gateway service
+
----
curl $GATEWAY_URL 
----

. You should see the following output
+
----
TODO:
----

== Congratulations!

In this lab you deployed microservices to OpenShift. In the next lab, you will learn how to leverage these microservices in a service mesh with Istio.

== References

* https://openshift.com[Red Hat OpenShift, window="_blank"]
* https://learn.openshift.com/servicemesh[Learn Istio on OpenShift, window="_blank"]
* https://istio.io[Istio Homepage, window="_blank"]