:noaudio:
:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= Deploying Microservices

== Lab Overview

There are three microservices in this lab and they are chained together in the following sequence:

`gateway -> partner -> catalog`

== Goals

In this lab, you will:

* Access the OpenShift environment
* Deploy microservice applications to OpenShift

=== OpenShift access

. Create a new tutorial project
+
----
oc new-project $OCP_TUTORIAL_PROJECT
----

. Set up permissions for the project
+
----
oc adm policy add-scc-to-user privileged -z default -n $OCP_TUTORIAL_PROJECT
----

. Switch to the tutorial project
+
----
oc project $OCP_TUTORIAL_PROJECT
----

== Clone Source Code

Start by cloning the tutorial source files to your computer.

. Open a terminal window and enter the following commands:
+
----
cd ~/lab

git clone https://github.com/gpe-mw-training/rhte-msa-and-service-mesh.git

cd rhte-msa-and-service-mesh
----

== Deploy Catalog service version 1 (`v1`)

Istio introduces the concept of a service version, which is a finer-grained way to subdivide
service instances by versions (`v1`, `v2`) or environment (`staging`, `prod`). These variants are not
necessarily different API versions: they could be iterative changes to the same service, deployed
in different environments (prod, staging, dev, etc.). Common scenarios where this is used include
A/B testing or canary rollouts. Istio’s https://istio.io/docs/concepts/traffic-management/rules-configuration.html[traffic routing rules, window="_blank"] can refer to service versions to
provide additional control over traffic between services.

Now let's start by deploying the catalog service to OpenShift. The sidecar proxy will automatically be injected.

. In your terminal window, enter the following commands:
+
----
cd catalog/java/vertx
mvn clean package
docker build -t example/catalog:v1 .
docker images | grep catalog

oc apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n $OCP_TUTORIAL_PROJECT
oc create -f ../../kubernetes/Service.yml
----

. Monitor the deployment of the pods. Enter the following command:
+
----
oc get pods -w
----
+
* For the `catalog` service, wait until the Ready column has `2/2` pods and the Status column has `Running`. 

* Expect to see:
+
----
NAME                          READY     STATUS    RESTARTS   AGE
catalog-v1-6b576ffcf8-g6b48   2/2       Running   0          1m
----

* To exit, press Ctrl+C.

Since the catalog service is at the end of our service chain (`gateway -> partner -> catalog`), it is not exposed to the outside world.

== Deploy Partner service 

Next, we will deploy the partner service to OpenShift. 

. In your terminal window, enter the following commands:
+
----
cd ~/lab/rhte-msa-and-service-mesh

cd partner/java/springboot
mvn clean package
docker build -t example/partner:v1 .
docker images | grep partner

oc apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n $OCP_TUTORIAL_PROJECT
oc create -f ../../kubernetes/Service.yml
----

. Monitor the deployment of the pods. Enter the following command:
+
----
oc get pods -w
----
+
* For the `partner` service, wait until the Ready column has `2/2` pods and the Status column has `Running`. 

* Expect to see:
+
----
NAME                          READY     STATUS    RESTARTS   AGE
partner-v1-68b4854c79-s5vnd   2/2       Running   0          2m
...
----

* To exit, press Ctrl+C.


== Deploy Gateway service

Finally, we will deploy the gateway service to OpenShift. This will complete our list of services: 

`gateway -> partner -> catalog`

. In your terminal window, enter the following commands:
+
----
cd ~/lab/rhte-msa-and-service-mesh

cd gateway/java/springboot
mvn clean package
docker build -t example/gateway .
docker images | grep gateway

oc apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n $OCP_TUTORIAL_PROJECT
oc create -f ../../kubernetes/Service.yml -n $OCP_TUTORIAL_PROJECT
----

. Monitor the deployment of the pods. Enter the following command:
+
----
oc get pods -w
----
+
* For the `gateway` service, wait until the Ready column has `2/2` pods and the Status column has `Running`. 

* Expect to see:
+
----
NAME                          READY     STATUS    RESTARTS   AGE
gateway-7b6bb9dcf7-zb8br      2/2       Running   0          1m
...
----

* To exit, press Ctrl+C.

=== Expose Gateway Service

. Since the `gateway` service is the one our users will interact with, let’s add an OpenShift Route that exposes that endpoint.
+
----
oc expose service gateway
----

. Retrieve the URL for the gateway service
+
----
export GATEWAY_URL=http://$(oc get route gateway -n $OCP_TUTORIAL_PROJECT -o template --template='{{.spec.host}}')

echo $GATEWAY_URL
----

. Test the gateway service
+
----
curl $GATEWAY_URL 
----
+
* You should see the following output
+
----
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 1
----

== Congratulations!

In this lab you deployed microservices to OpenShift. In the next lab, you will learn how to leverage these microservices in a service mesh with Istio.

== References

* https://openshift.com[Red Hat OpenShift, window="_blank"]
* https://learn.openshift.com/servicemesh[Learn Istio on OpenShift, window="_blank"]
* https://istio.io[Istio Homepage, window="_blank"]