:noaudio:
:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= Dynamic Routing with Istio

== What is a Service Mesh?

As microservices-based applications become more prevalent, both the number of
and complexity of their interactions increases. Up until now much of the burden
of managing these complex microservices interactions has been placed on the
application developer, with different or non-existent support for microservice
concepts depending on language and framework.

The service mesh concept pushes this responsibility to the infrastructure, with
features for traffic management, distributed tracing and observability, policy
enforcement, and service/identity security, freeing the developer to focus on
business value. In this hands-on session you will learn how to apply some of
these features to a simple polyglot microservices application running on top of
OpenShift using Istio, an open platform to connect, manage, and secure
microservices.

== What is Istio?

Istio is an open platform to connect, manage, and secure microservices. Istio
provides an easy way to create a network of deployed services with load
balancing, service-to-service authentication, monitoring, and more, without
requiring any changes in application code. OpenShift can automatically inject a
special sidecar proxy throughout your environment to enable Istio management for
your application. This proxy intercepts all network communication between your
microservices microservices, and is configured and managed using Istio’s control
plane functionality -- not your application code!

== Lab Overview

There are three microservices in this lab and they are chained together in the following sequence:

`gateway -> partner -> catalog`

In this lab you'll dynamically alter routing between the services using Istio.

== Goals

In this lab, you will learn how to:

* Inject sidecar proxies into applications which form a service mesh
* Configure a service mesh to dynamically route and shape traffic to and from services

== Deploy Catalog service version 2 (`v2`)

We can experiment with Istio routing rules by deploying a second version of the catalog
service.

. Edit Java source code to show v2 message
+
----
cd ~/lab/rhte-msa-and-service-mesh/catalog/java/vertx

vi src/main/java/com/redhat/developer/demos/catalog/CatalogVerticle.java
----

. In the file `CatalogVerticle.java`, update this line to say `v2`
+
----
private static final String RESPONSE_STRING_FORMAT = "catalog v2 from '%s': %d\n";
----

. Save the file and exit vi.

. Build the service with the following commands:
+
----
mvn clean package

docker build -t example/catalog:v2 .
----
+
NOTE: The "v2" tag during the Docker build is significant.

. Deploy Catalog service version 2 
+
----
oc apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment-v2.yml) -n $OCP_TUTORIAL_PROJECT
----
+
* This second deployment file `Deployment-v2.yml` will label the service correctly.

. You can see both versions of the `catalog` pods running with the following command:
+
----
oc get pods -l app=catalog
----
+
* You should see:
+
----
NAME                          READY     STATUS    RESTARTS   AGE
catalog-v1-6b576ffcf8-g6b48   2/2       Running   0          31m
catalog-v2-7764964564-hj8xl   2/2       Running   0          49s
----
+
* By default, Istio will round-robin incoming requests to the `catalog` Service
so that both `v1` and `v2` pods get equal amounts of traffic.

. Make sure your environment variable for $GATEWAY_URL is still set.
+
----
echo $GATEWAY_URL
----

. Test the gateway service
+
----
curl $GATEWAY_URL
----
+
* You will likely see:
+
----
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 2
----
+
* Where `6b576ffcf8-g6b48` is the pod running `v1` and the `2` is the number of times you hit the endpoint.

. Make another request to the gateway service
+
----
gateway => partner => catalog v2 from '7764964564-hj8xl': 1
----
+
* Where `7764964564-hj8xl` is the pod running `v2` and the `1` is basically the number of times you hit the endpoint.

* By default you get round-robin load-balancing when there is more than one Pod behind a Service

. Send severals to the gateway service. 
+
----
~/rhte-msa-and-service-mesh/scripts/run.sh
----
+
* The `run.sh` script will loop and send 10 requests to the gateway service.

* You should see:
+
----
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 4
gateway => partner => catalog v2 from '7764964564-hj8xl': 3
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 5
gateway => partner => catalog v2 from '7764964564-hj8xl': 4
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 6
gateway => partner => catalog v2 from '7764964564-hj8xl': 5
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 7
gateway => partner => catalog v2 from '7764964564-hj8xl': 6
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 8
gateway => partner => catalog v2 from '7764964564-hj8xl': 7
----
+
* Approximately half of the requests above go to `v1` and the other half to `v2`.

* The default Kubernetes/OpenShift behavior is to round-robin load-balance across all
available pods behind a single Service. 

. Scale up the number of pods for the `catalog-v2` pod:
+
----
oc scale --replicas=2 deployment/catalog-v2
----

. Now let's send in 10 requests
+
----
~/rhte-msa-and-service-mesh/scripts/run.sh
----

* You should see:
+
----
gateway => partner => catalog v2 from '7764964564-hj8xl': 8
gateway => partner => catalog v2 from '7764964564-d8qwp': 1
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 9
gateway => partner => catalog v2 from '7764964564-hj8xl': 9
gateway => partner => catalog v2 from '7764964564-d8qwp': 2
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 10
gateway => partner => catalog v2 from '7764964564-hj8xl': 10
gateway => partner => catalog v2 from '7764964564-d8qwp': 3
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 11
gateway => partner => catalog v2 from '7764964564-hj8xl': 11
----
+
* Notice that *double* the number of requests are sent to `v2` than for `v1`:

. Scale back to a single pod for the `catalog-v2` deployment:
+
----
oc scale --replicas=1 deployment/catalog-v2
----

. Run the test again and confirm that the requests are split evenly between `v1` and `v2`.

== Send all traffic to `catalog:v2`

_Route rules_ control how requests are routed within an Istio service mesh.

Requests can be routed based on the source and destination, HTTP header fields, and weights associated with individual service versions. For example, a route rule could route requests to different versions of a service.

In addition to the usual OpenShift object types like `BuildConfig`, `DeploymentConfig`,
`Service` and `Route`, you also have new object types installed as part of Istio like `RouteRule`. Adding these objects to the running OpenShift cluster is how you configure routing rules for Istio.

. Route all traffic to `v2`:
+
----
cd ~/lab/rhte-msa-and-service-mesh

istioctl create -f istiofiles/destination-rule-catalog-v1-v2.yml -n $OCP_TUTORIAL_PROJECT
istioctl create -f istiofiles/virtual-service-catalog-v2.yml -n $OCP_TUTORIAL_PROJECT
----

. Test the `gateway` service again - all requests should end up talking to
`catalog:v2`:
+
----
scripts/run.sh
----
+
* You should see:
+
----
gateway => partner => catalog v2 from '7764964564-hj8xl': 17
gateway => partner => catalog v2 from '7764964564-hj8xl': 18
gateway => partner => catalog v2 from '7764964564-hj8xl': 19
gateway => partner => catalog v2 from '7764964564-hj8xl': 20
gateway => partner => catalog v2 from '7764964564-hj8xl': 21
gateway => partner => catalog v2 from '7764964564-hj8xl': 22
gateway => partner => catalog v2 from '7764964564-hj8xl': 23
gateway => partner => catalog v2 from '7764964564-hj8xl': 24
gateway => partner => catalog v2 from '7764964564-hj8xl': 25
gateway => partner => catalog v2 from '7764964564-hj8xl': 26
----
+
* You should only see `v2` being returned.

== Send all traffic to `catalog:v1`

. Now let's move everyone to catalog service `v1`:
+
----
oc replace -f istiofiles/virtual-service-catalog-v1.yml -n $OCP_TUTORIAL_PROJECT
----
+
NOTE: We use `oc replace` instead of `oc create` since we are overlaying the previous rule

. Now let's send in 10 requests:
+
----
scripts/run.sh
----
+
* You should see:
+
----
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 17
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 18
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 19
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 20
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 21
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 22
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 23
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 24
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 25
gateway => partner => catalog v1 from '6b576ffcf8-g6b48': 26
----
+
* Notice how all requests now to go `v1`.

. Remove the route rules to get back to default round-robin distribution
of requests.
+
----
oc delete -f istiofiles/virtual-service-catalog-v1.yml -n $OCP_TUTORIAL_PROJECT
----

. Now let's send in 10 requests:
+
----
scripts/run.sh
----
+
* Traffic should be equally split once again between `v1` and `v2`.

== Use a Canary Deployment to slowly rollout `v2`

Canary Deployment scenario: push v2 into the cluster but slowly send end-user traffic to it, if you continue to see success, continue shifting more traffic over time.

. Create the virtualservice that will send 75% of requests to v1 and 25% to v2:
+
----
istioctl create -f istiofiles/virtual-service-catalog-v1_and_v2_75_25.yml -n $OCP_TUTORIAL_PROJECT
----

. And issue 10 requests:
+
----
scripts/run.sh
----
+ 
* Now you should see 2 or 3 requests (~25%) going to `v2`. This process can be continued (and automated), slowly migrating
traffic over to the new version as it proves its worth in production over time.

== Clean Up

. Remove the route rules before moving on:
+
----
scripts/clean.sh $OCP_TUTORIAL_PROJECT
----

== Congratulations!

In this lab you learned how to deploy microservices to form a _service mesh_ using Istio.
You also learned how to do traffic shaping and routing using _Route Rules_ which instruct
the Istio sidecar proxies to distribute traffic according to specified policy.

== References

* https://openshift.com[Red Hat OpenShift, window="_blank"]
* https://learn.openshift.com/servicemesh[Learn Istio on OpenShift, window="_blank"]
* https://istio.io[Istio Homepage, window="_blank"]