:noaudio:
:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= Circuit Breaker Lab

== Lab Overview

This exercise shows how to inject faults and test the resiliency of your application. Istio provides a set of failure recovery features that can be taken advantage of by the services in an application. Features include:

    Timeouts
    Bounded retries with timeout budgets and variable jitter between retries
    Limits on number of concurrent connections and requests to upstream services
    Active (periodic) health checks on each member of the load balancing pool
    Fine-grained circuit breakers (passive health checks) – applied per instance in the load balancing pool

Together, these features enable the service mesh to tolerate failing nodes and prevent localized failures from cascading instability to other nodes.

== Goals

In this lab, you will learn how to:

* Implement the pool ejection resilience strategy to increase the overall availability
* Leverage the circuit breaker pattern to avoid multiple concurrent requests to an instance


[NOTE]
._Before Start_
====
You should have NO virtualservice nor destinationrule (in tutorial namespace) istioctl get virtualservice istioctl get destinationrule if so run:

----
cd ~/rhte-msa-and-service-mesh/

./scripts/clean.sh $OCP_TUTORIAL_PROJECT
----

== Update Application Code

In this section, you will update the CatalogVerticle to expose additional endpoints for testing

. Edit the file with the following commands:
+
----
cd ~/rhte-msa-and-service-mesh/catalog/java/vertex

vi src/main/java/com/redhat/developer/demos/catalog/CatalogVerticle.java
----

. Uncomment the line `router.get("/").handler(this::timeout);`

. Save the file and exit vi using `ESC` + `:wq`

. Build the service with the following commands:
+
----
mvn clean package

docker build -t example/catalog:v2 .
----

. Deploy Catalog service version 2 
+
----
oc delete pod -l app=catalog-service,version=v2
----
+
* Why the delete pod? Based on the Deployment configuration, Kubernetes/OpenShift will recreate the pod, based on the new docker image as it attempts to keep the desired replicas available.

. You can see both versions of the catalog pods running using `oc get pods`:
+
----
oc get pods -l app=catalog

NAME                                 READY     STATUS    RESTARTS   AGE
catalog-v1-60483540-9snd9     2/2       Running   0          12m
catalog-v2-2815683430-vpx4p   2/2       Running   0          15s
----



== Pool Ejection

=== Test behavior without failing instances

=== Test behavior with failing instance and without pool ejection

=== Test behavior with failing instance and with pool ejection

== Ultimate resilience with retries, circuit breaker, and pool ejection



====

== References

* https://openshift.com[Red Hat OpenShift, window="_blank"]
* https://learn.openshift.com/servicemesh[Learn Istio on OpenShift, window="_blank"]
* https://istio.io[Istio Homepage, window="_blank"]